### ISSUE TITLE
Can't install equatable_gen because of version constraints

### ISSUE THREAD

**Issue by techouse** [mrgnhnt96/equatable_gen#1]
Adding this to pubspec.yaml

```yaml
dependencies:
  equatable_annotations: ^1.0.0

dev_dependencies:
  equatable_gen: ^1.0.1
```

Will fail with this error

```
Because every version of equatable_gen depends on equatable_annotations >=0.1.0 <1.0.0 and my_new_project depends on equatable_annotations ^1.0.0, equatable_gen is forbidden.
So, because my_new_project depends on equatable_gen ^1.0.0, version solving failed.
```
